menu:
  Home: /
  About: http://rahmat.budiharso.info
  Github: https://github.com/rbudiharso
  archive: /archives

favicon: /favicon.png
logo: /favicon.png

# comment
disqus: blogbudiharsoinfo

# google-analytics:
ga: UA-47454066-1
