menu:
  Home: /
  About: http://rahmat.budiharso.info
  Github: https://github.com/rbudiharso
  archive: /archives

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: blogbudiharsoinfo

# Analytics
# google-analytics:
ga: UA-47454066-1

# Copyright Infomation
startyear: 2012
